# Generated by Django 4.2.5 on 2023-09-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_propic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='propic',
        ),
        migrations.AddField(
            model_name='video',
            name='author_image',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
